app/__init__.py
from flask import Flask
import os

def create_app():
    # Create the Flask application
    app = Flask(__name__)

    # Load configuration from config.py
    app.config.from_pyfile(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'config.py'))

    # Import and register blueprints (if any)
    from app.routes import main_bp
    app.register_blueprint(main_bp)

    return app

app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
import sqlite3
from flask import jsonify


main_bp = Blueprint('main', __name__)

# SQLite database file
database_file = 'pro_mma_data.db'

@main_bp.route('/')
def index():
    # Connect to the SQLite database
    conn = sqlite3.connect(database_file)
    cursor = conn.cursor()

    # Retrieve information about each event and group by event_title
    cursor.execute('''
        SELECT
            event_title,
            organisation,
            COUNT(*) AS TotalFights,
            ROUND(AVG(round), 2) AS AverageRounds,
            MAX(time) AS LongestFightTime
        FROM fights
        GROUP BY event_title, organisation
        ORDER BY date DESC LIMIT 15
    ''')

    event_info = cursor.fetchall()
    event_columns = ['Event Title', 'Organisation', 'Total Fights', 'Average Rounds', 'Longest Fight Time']

    # Retrieve fighter rankings
    cursor.execute('''
        SELECT 
            fighter_name,
            nickname,
            age,
            weight_class,
            wins,
            losses,
            win_percentage
        FROM fighters 
        ORDER BY wins DESC LIMIT 20
    ''')
    fighter_rankings = cursor.fetchall()
    fighters_columns = ['Fighter Name', 'Nickname', 'Age', 'Weight Class', 'Wins', 'Losses', 'Win Percentage']

    # Close the database connection
    conn.close()

    return render_template('index.html', event_info=event_info, event_columns=event_columns,
                           fighter_rankings=fighter_rankings, fighters_columns=fighters_columns)

@main_bp.route('/fighter/<fighter_name>')
def fighter_details(fighter_name):
    # Connect to the SQLite database
    conn = sqlite3.connect(database_file)
    cursor = conn.cursor()

    # Retrieve fighter details
    cursor.execute('SELECT * FROM fighters WHERE fighter_name = ?', (fighter_name,))
    fighter_details = cursor.fetchone()
    columns = ['Fighter Name', 'Nickname', 'Birth Date', 'Age', 'Death Date',
       'Location', 'Country', 'Height', 'Weight', 'Association',
       'Weight Class', 'Wins', 'Wink by KO', 'Wins by Submission', 'Wins by Decision',
       'Wins Other', 'Losses', 'Losses by KO', 'Losses by Submission',
       'Losses by Decision', 'Losses Other', 'Height (cm)', 'Weight (kg)',
       'Win Percentage', 'BMI', 'Submission Ratio', 'KO Ratio',
       'Decision Ratio']

    # Retrieve fighter's latest fights
    cursor.execute('SELECT * FROM fights WHERE fighter1_name = ? OR fighter2_name = ? ORDER BY date DESC LIMIT 10',
                   (fighter_name, fighter_name))
    fighter_latest_fights = cursor.fetchall()
    fights_columns = ['Id', 'Event Name', 'Organisation', 'Date', 'Location', 'Match Nr.', 'Fighter 1 Name', 'Fighter 2 Name', 'Fighter 1 Result', 'Fighter 2 Result', 'Win Method', 'Win Details', 'Referee', 'Round', 'Time']

    # Close the database connection
    conn.close()

    return render_template('fighter_details.html', fighter_details=fighter_details, columns=columns,
                           fighter_latest_fights=fighter_latest_fights, fights_columns=fights_columns)

@main_bp.route('/fighter_rankings', methods=['GET', 'POST'])
def fighter_rankings():
    return 404

@main_bp.route('/event/<event_title>')
def event_details(event_title):
    # Connect to the SQLite database
    conn = sqlite3.connect(database_file)
    cursor = conn.cursor()
    
    cursor.execute('''
        SELECT
            event_title,
            organisation,
            COUNT(*) AS TotalFights,
            ROUND(AVG(round), 2) AS AverageRounds,
            ROUND(AVG(time)) AS AverageTime,
            MAX(time) AS LongestFightTime
        FROM fights
        GROUP BY event_title, organisation
        ORDER BY date DESC LIMIT 20
    ''')
    event_details = cursor.fetchall()
    event_columns = ['Event Name', 'Organisation', 'Total Fights', 'Avg. Rounds', 'Avg. Time', 'Max Fight Time']

    # Retrieve fights for the event
    cursor.execute('SELECT * FROM fights WHERE event_title = ? ORDER BY date ASC', (event_title,))
    event_fights = cursor.fetchall()
    fights_columns = ['Id', 'Event Name', 'Organisation', 'Date', 'Location', 'Match Nr.', 'Fighter 1 Name', 'Fighter 2 Name', 'Fighter 1 Result', 'Fighter 2 Result', 'Win Method', 'Win Details', 'Referee', 'Round', 'Time']


    # Close the database connection
    conn.close()

    return render_template('event_details.html', event_details=event_details, event_columns=event_columns ,event_fights=event_fights, fights_columns=fights_columns)

@main_bp.route('/filter_events', methods=['GET'])
def filter_events():
    if request.method == 'GET':
        # Handle AJAX request and return filtered data
        event_name_filter = request.args.get('event_name')
        search_term_filter = request.args.get('search_term')

        # Connect to the SQLite database
        conn = sqlite3.connect(database_file)
        cursor = conn.cursor()

        # Perform filtering logic and retrieve filtered data
        cursor.execute('''
            SELECT
                event_title,
                organisation,
                COUNT(*) AS TotalFights,
                ROUND(AVG(round), 2) AS AverageRounds,
                MAX(time) AS LongestFightTime
            FROM fights
            WHERE event_title LIKE ? AND organisation LIKE ?
            GROUP BY event_title, organisation
            ORDER BY date DESC LIMIT 15
        ''', ('%' + event_name_filter + '%', '%' + search_term_filter + '%'))

        filtered_data = cursor.fetchall()

        # Close the database connection
        conn.close()

        # Return filtered data as JSON
        return jsonify(filtered_data)

@main_bp.route('/filter_fighters', methods=['GET'])
def filter_fighters():
    if request.method == 'GET':
        fighter_name_filter = request.args.get('fighter_name')
        association_name_filter = request.args.get('association_name')

        conn = sqlite3.connect(database_file)
        cursor = conn.cursor()

        cursor.execute('''
            SELECT
                fighter_name,
                nickname,
                age,
                weight_class,
                wins,
                losses,
                win_percentage
            FROM fighters
            WHERE fighter_name LIKE ? OR association LIKE ?
            ORDER BY wins DESC LIMIT 20
            ''', ('%' + fighter_name_filter + '%', '%' + association_name_filter + '%'))
        
        filtered_data = cursor.fetchall()

        conn.close()

        # Return filtered data as JSON
        return jsonify(filtered_data)

app/templates/event_details.html
{% extends 'layout.html' %}

{% block content %}
    <section id="event_details">
        <h2>Event Details</h2>
        <table border="1">
            <tr>
                {% for column in event_columns %}
                    <th>{{ column }}</th>
                {% endfor %}
            </tr>
            <tr>
                {% for value in event_details %}
                    <td>{{ value }}</td>
                {% endfor %}
            </tr>
        </table>
    </section>

    <section id="event_fights">
        <h2>Event Fights</h2>
        <table border="1">
            <tr>
                {% for column in fights_columns %}
                    <th>{{ column }}</th>
                {% endfor %}
            </tr>
            {% for row in event_fights %}
                <tr>
                    {% for value in row %}
                        <td>{{ value }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </section>
{% endblock %}

app/templates/fighter_details.html
{% extends 'layout.html' %}

{% block content %}
    <section id="fighter_details">
        <div id="container text-center mt-4">
        <h2>Fighter Details</h2>
        <table class="table table-borderless table-style mt-4">
            <tr>
                {% for col in columns %}
                    <th>{{ col.capitalize() }}</th>
                {% endfor %}
            </tr>
            <tr>
                {% for value in fighter_details %}
                    <td>{{ value }}</td>
                {% endfor %}
            </tr>
        </table>
        </div>
    </section>

    <section id="fighter_latest_fights">
        <div id="container text-center mt-4">
        <h2>Fighter's Latest Fights</h2>
        <table class="table table-bordered table-striped table-style">
            <tr>
                {% for col in fights_columns %}
                    <th>{{ col.capitalize() }}</th>
                {% endfor %}
            </tr>
            {% for row in fighter_latest_fights %}
                <tr>
                    {% for value in row %}
                        <td>{{ value }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
        </div>
    </section>
{% endblock %}

app/templates/fighter_rankings.html
{% extends 'layout.html' %}

{% block content %}
    <section id="fighter_rankings">
        <h2>Fighter Rankings</h2>
        <form method="post" action="{{ url_for('main.fighter_rankings') }}">
            <label for="filter_name">Filter by Name:</label>
            <input type="text" name="filter_name" id="filter_name">
            <label for="search_term">Search:</label>
            <input type="text" name="search_term" id="search_term">
            <button type="submit">Apply Filters</button>
        </form>
        <table class="table table-bordered table-striped">
            <tr>
                {% for column in fighters_columns %}
                    <th>{{ column.capitalize() }}</th>
                {% endfor %}
            </tr>
            {% for row in fighter_rankings %}
                <tr>
                    {% for data in row %}
                    <td>{{ data }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </section>
{% endblock %}

app/templates/filtered_data.html
{% extends 'layout.html' %}

{% block content %}
    <section id="event_info">
        <div class="containe-fluid">
            <h2>Event Information</h2>
            <table class="table table-hover table-responsive" id="eventTable">
                <thead>
                    <tr>
                        {% for column in event_columns %}
                        <th scope="col">{{ column }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for row in filtered_data.events %}
                    <tr>
                        {% for data in row %}
                            {% if loop.index == 1 %}
                            <td scope="row"><a href="{{ url_for('main.event_details', event_title=data) }}">{{ data }}</a></td>
                            {% else %}
                            <td scope="row">{{ data }}</td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    {% endfor %}
                    {% if not filtered_data.events %}
                        {# Show full list if no filtered events #}
                        {% for row in event_info %}
                        <tr>
                            {% for data in row %}
                                {% if loop.index == 1 %}
                                <td scope="row"><a href="{{ url_for('main.event_details', event_title=data) }}">{{ data }}</a></td>
                                {% else %}
                                <td scope="row">{{ data }}</td>
                                {% endif %}
                            {% endfor %}
                        </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
    </section>

    <section id="fighter_rankings">
        <div class="container-fluid">
            <h2>Fighter Information</h2>
            <table class="table table-hover table-responsive" id="fighterTable">
                <thead>
                    <tr>
                        {% for column in fighters_columns %}
                        <th scope="col">{{ column }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for row in filtered_data.fighters %}
                    <tr>
                        {% for data in row %}
                            {% if loop.index == 1 %}
                            <td scope="row"><a href="{{ url_for('main.fighter_details', fighter_name=data) }}">{{ data }}</a></td>
                            {% else %}
                            <td scope="row">{{ data }}</td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    {% endfor %}
                    {% if not filtered_data.fighters %}
                        {# Show full list if no filtered fighters #}
                        {% for row in fighter_rankings %}
                        <tr>
                            {% for data in row %}
                                {% if loop.index == 1 %}
                                <td scope="row"><a href="{{ url_for('main.fighter_details', fighter_name=data) }}">{{ data }}</a></td>
                                {% else %}
                                <td scope="row">{{ data }}</td>
                                {% endif %}
                            {% endfor %}
                        </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
    </section>
{% endblock %}

app/templates/index.html
{% extends 'layout.html' %}

{% block content %}
    <section id="event_info">
        <div class="containe-fluid">
            <h2>Event Information</h2>
            <form method="GET" id="eventFilterForm">
                <label for="event_name">Filter by Event Name:</label>
                <input type="text" name="event_name" id="event_name"><br>
                <label for="organisation_name">Filter by Organization:</label>
                <input type="text" name="organisation_name">
                <button type="submit" id="submit_event_filter">Apply Filters</button>
            </form>
            <table class="table table-hover table-responsive" id="eventTable">
                <thead>
                    <tr>
                        {% for column in event_columns %}
                        <th scope="col">{{ column }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for row in event_info %}
                    <tr>
                        {% for data in row %}
                            {% if loop.index == 1 %}
                            <td scope="row"><a href="{{ url_for('main.event_details', event_title=data) }}">{{ data }}</a></td>
                            {% else %}
                            <td scope="row">{{ data }}</td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </section>

    <section id="fighter_rankings">
        <div class="container-fluid">
            <h2>Fighter Information</h2>
            <form method="GET" id="fighterRankingsForm">
                <label for="fighter_name">Filter by Fighter Name:</label>
                <input type="text" name="fighter_name" id="fighter_name"><br>
                <label for="association_name">Filter by Association:</label>
                <input type="text" name="association_name" id="association_name">
                <button type="submit" id="submit_fighter_filter">Apply Filters</button>
            </form>
            <table class="table table-hover table-responsive" id="fighterTable">
                <thead>
                    <tr>
                        {% for column in fighters_columns %}
                        <th scope="col">{{ column }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for row in fighter_rankings %}
                    <tr>
                        {% for data in row %}
                            {% if loop.index == 1 %}
                            <td scope="row"><a href="{{ url_for('main.fighter_details', fighter_name=data) }}">{{ data }}</a></td>
                            {% else %}
                            <td scope="row">{{ data }}</td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MatchMaking</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

    <!-- Bootstrap JS and Popper.js (required for Bootstrap dropdowns and modals) -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

    <!-- Local CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md border">
        <div class="container-fluid">
            <h1>MatchMaking</h1>
            <ul class="navbar-nav me-auto mt-2">
                <li class="nav-item"><a href="/" style="color:beige" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="/web-app/app/templates/fighter_rankings.html" style="color:beige;" class="nav-link">Fighter Rankings</a></li>
                <li class="nav-item"><a href="/fighter_details.html" style="color:beige;" class="nav-link">Compare Fighters<span style="color:red">(NEW!)</span></a></li>
            </ul>
        </nav>
        </div>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

</body>
</html>